knitsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patrons/', include('patrons.urls')),
    path('', RedirectView.as_view(url='/patrons'), name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patrons/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.patron, name='patron'),
    path('pull/', views.pull, name='pull'),
    path('bonnet/', views.bonnet, name='bonnet'),
    path('gant/', views.gant, name='gant'),
    path('echarpe/', views.echarpe, name='echarpe'),
]

patrons/models.py
from django.db import models
from . import settings
from django.core.files.storage import FileSystemStorage
import re


class Patron(models.Model):
	category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="Catégorie")
	name = models.CharField(max_length=200, verbose_name="Nom")
	image = models.ImageField('Photo', null=True, upload_to='img', storage=FileSystemStorage(location=settings.MEDIA_ROOT, base_url=''))

	def __str__(self):
		return self.name

class Pelote(models.Model):
	patron = models.ForeignKey(Patron, null=True, on_delete=models.CASCADE)
	name = models.CharField(max_length=200, default="", verbose_name="Nom")
	quantity = models.IntegerField(default=0, verbose_name="Quantité")
	color = models.CharField(max_length=200, verbose_name="Colori")

	def __str__(self):
		return "Pelote"

class Aiguille(models.Model):
	patron = models.ForeignKey(Patron, null=True, on_delete=models.CASCADE)
	type = models.CharField(max_length=200, verbose_name="Type d'aiguille")
	size = models.FloatField(default=0, verbose_name="Taille d'aiguille")

	def __str__(self):
		return "Aiguille"

class Etape(models.Model):
	patron = models.ForeignKey(Patron, null=True, on_delete=models.CASCADE)
	text = models.TextField('Etape', max_length=200, null=True)
	schema = models.ImageField('Photo', blank=True, null=True, upload_to='img', storage=FileSystemStorage(location=settings.MEDIA_ROOT, base_url=''))

	def __str__(self):
		return "Etape"

class Echantillon(models.Model):
	patron = models.ForeignKey(Patron, null=True, on_delete=models.CASCADE)
	nb_mailles = models.IntegerField(default=0, verbose_name="Nombre de mailles")
	nb_rangs = models.IntegerField(default=0, verbose_name="Nombre de rangs")
	aiguille = models.CharField(max_length=200, default="", verbose_name="Taille d'aiguille")
	point = models.CharField(max_length=300, default="", verbose_name="Type de point")

	def __str__(self):
		return "Echantillon"

class Category(models.Model):
	name = models.CharField(max_length=30)

	def __str__(self):
		return self.name

patrons/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Patron, Category


def index(request):
    list = Patron.objects.all()
    category_list = Category.objects.all()
    context = {'list': list, 'cat':'index', 'category_list':category_list}
    return render(request, 'patrons/index.html', context)

def pull(request):
    list = Patron.objects.filter(category__name__contains="pull")
    category_list = Category.objects.all()
    context = {'cat': "Pull", 'list': list, 'category_list':category_list}
    return render(request, 'patrons/category.html', context)

def bonnet(request):
    list = Patron.objects.filter(category__name__contains="bonnet")
    category_list = Category.objects.all()
    context = {'cat': "Bonnet", 'list': list, 'category_list':category_list}
    return render(request, 'patrons/category.html', context)

def gant(request):
    list = Patron.objects.filter(category__name__contains="gant")
    category_list = Category.objects.all()
    context = {'cat': "Gant", 'list': list, 'category_list':category_list}
    return render(request, 'patrons/category.html', context)

def echarpe(request):
    list = Patron.objects.filter(category__name__contains="echarpe")
    category_list = Category.objects.all()
    context = {'cat': "Echarpe", 'list': list, 'category_list':category_list}
    return render(request, 'patrons/category.html', context)

def patron(request, id):
    patron = get_object_or_404(Patron, id=id)
    category_list = Category.objects.all()
    context = {'cat': patron.category, 'patron': patron, 'category_list':category_list}
    return render(request, 'patrons/patron.html', context)

patrons/templates/patrons/category.html
{% extends "base.html" %}
{% block title %} {{ cat }} {% endblock %}

{% load static %}



{% block content %}
	<div class="container">
	  
		<div class="row">
	  	{% for model in list %}

		
	    	<div class="col-sm">
	    		<figure class="figure-patron">
				    <a href="{% url 'patron' model.id %}"><img class="img-patron" src="../../static{{ model.image.url }}" height="300px" class="image" style="cursor: pointer;" alt={{ model.name }}></a>
				    <figcaption class="name-patron">{{ model.name }}</figcaption>
				</figure>
		    </div>
        
		{% empty %}
	    <p>Pas de {{ cat }} pour le moment !</p>

    	{% endfor %}
	    
	    </div>
	  
	</div>

    


{% endblock %}

patrons/templates/patrons/index.html
{% extends "base.html" %}
{% block title %}Accueil{% endblock %}



{% block content %}
	<div class="container">
	  
		<div class="row">
	  	{% for model in list %}

		
	    	<div class="col-sm">
	    		<figure class="figure-patron">
				    <a href="{% url 'patron' model.id %}"><img class="img-patron" src="../../static{{ model.image.url }}" height="300px" class="image" style="cursor: pointer;" alt={{ model.name }}></a>
				    <figcaption class="name-patron">{{ model.name }}</figcaption>
				</figure>
		    </div>
        
		{% empty %}
	    <p>Pas de {{ cat }} pour le moment !</p>

    	{% endfor %}
	    
	    </div>
	  
	</div>

    


{% endblock %}

patrons/templates/patrons/patron.html
{% extends "base.html" %}
{% block title %} {{ patron.name }} {% endblock %}

{% block content %}

<h2 class="h2-patron">{{ patron.name }}</h2>

<div class="container">
<div class="row">

    <div class="col-sm">
        <img src="../../static{{ patron.image.url }}" height="400px" style="cursor: pointer;">
    </div>

    <div class="col-sm">
        <h3 class="h3-patron">Fournitures</h3>

        <h4 class="h4-patron">Laine</h4>
        <ul style="list-style-type:disc;">
        {% for pelote in patron.pelote_set.all %}
            <li class="li-pelote">{{pelote.quantity}} pelote{{pelote.quantity | pluralize}} {{pelote.name}} {{pelote.color}}</li>
        {% endfor %}
        </ul>

        <h4 class="h4-patron">Aiguilles</h4>
        <!--<img src="../../static/img/aiguilles.png" height="20px" style="cursor: pointer;">-->
        <ul style="list-style-type:disc;">
        {% for aiguille in patron.aiguille_set.all %}
            <li class="li-aiguille"> Aiguille {{aiguille.type}} {{pelote.size}} </li>
        {% endfor %}
        </ul>

        <h3 class="h3-patron">Echantillon</h3>
        {% for echantillon in patron.echantillon_set.all %}
        <div class="row">
            <div class="col">
                <figure class="figure-echantillon">
                    <img class="img-echantillon" src="../../static/img/echantillon.png">
                    <figcaption class="nb-rangs-echantillon">{{ echantillon.nb_rangs }} rangs </figcaption>
                    <figcaption class="nb-mailles-echantillon">{{ echantillon.nb_mailles }} mailles</figcaption>
                </figure>
            </div>
            <div class="col">
                L'échantillon de 10 cm sur 10 cm correspond à {{echantillon.nb_mailles}} mailles sur {{echantillon.nb_rangs}} rangs, en tricotant en {{echantillon.points}} avec des aiguilles {{echantillon.aiguille}}.
            </div>
        </div>
            <div class="empty"></div>
            

        {% endfor %}
    </div>

</div>






<h3 class="h3-patron">Explications</h3>
<ol>
    {% for etape in patron.etape_set.all%}
        <li>{{ etape.text}}</li>
        {% if etape.schema %} 
            <img src="../../static{{ etape.schema.url }}" height="200px" style="cursor: pointer;">
        {% endif %}
        
    {% endfor %}
</ol>



{% endblock %}

</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Accueil{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"> 
    <link href="/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>


<h1>Mes Modèles de Tricot</h1>



<div class="topnav" id="topnav"> 
    {% block nav %} 
	<a class="{% if cat == "index" %}active{% endif %}" href="/patrons">Home</a>
    {% for category in category_list %}
	<a class="{% if cat|lower == category.name|lower %}active{% endif %}" href="/patrons/{{category.name|lower}}" id="pulllink">{{ category.name }}</a>
    {% endfor %}
    <a class="{% if cat == "En cours" %}active{% endif %}" href="#now">En cours</a>
	<a class="{% if cat == "admin" %}active{% endif %}" href="/admin" id="adminlink">Admin</a>
    {% endblock %}
</div> 



<section id="content">
    {% block content %}{% endblock %}
</section>



<!--<footer>&copy; Aloïs</footer>-->

</body>
</html>